from typing import Dict, List, Tuple

CARDS_PER_PAGE = 6
IMAGE_WIDTH = 300
IMAGE_HEIGHT = 200

DEFAULT_PRICE_RANGE = (0, 100000)
PRICE_STEP = 100
DEFAULT_ITEMS_PER_PAGE = 10
ITEMS_PER_PAGE_OPTIONS = [10, 25, 50, 100]
MAX_RETRIES = 3

ERROR_MESSAGES = {
    "api_error": "An error occurred while searching eBay. Please try again later.",
    "invalid_category": "Invalid category selected. Please try again.",
    "invalid_subcategory": "Invalid subcategory selected. Please try again.",
    "search_failed": "Search failed. Please check your parameters and try again.",
    "session_error": "Session error. Please refresh the page and try again."
}

CATEGORIES: Dict[str, List[str]] = {
    "All Categories": [],
    "Electronics": [
        "Computers & Tablets",
        "Cell Phones & Accessories",
        "Cameras & Photo",
        "TV, Video & Audio",
        "Video Games & Consoles",
        "Smart Home & Security",
        "Computer Components",
        "Networking",
        "Printers & Scanners",
        "Computer Accessories",
        "Audio Equipment",
        "Drones & Accessories",
        "Virtual Reality",
        "Wearable Technology",
        "Electronic Accessories"
    ],
    "Fashion": [
        "Men's Clothing",
        "Women's Clothing",
        "Shoes",
        "Jewelry & Watches",
        "Bags & Accessories",
        "Kids' Clothing",
        "Men's Accessories",
        "Women's Accessories",
        "Men's Shoes",
        "Women's Shoes",
        "Kids' Shoes",
        "Men's Watches",
        "Women's Watches",
        "Men's Jewelry",
        "Women's Jewelry",
        "Sunglasses",
        "Hats & Caps",
        "Belts & Suspenders",
        "Ties & Bow Ties",
        "Scarves & Wraps"
    ],
    "Home & Garden": [
        "Furniture",
        "Home Décor",
        "Kitchen & Dining",
        "Bedding & Bath",
        "Garden & Outdoor",
        "Tools & Home Improvement",
        "Lighting",
        "Rugs & Carpets",
        "Wall Art",
        "Window Treatments",
        "Storage & Organization",
        "Cleaning Supplies",
        "Home Security",
        "Patio Furniture",
        "Grills & Outdoor Cooking",
        "Gardening Tools",
        "Plants & Seeds",
        "Pest Control",
        "Home Appliances",
        "Home Improvement Tools"
    ],
    "Sports & Leisure": [
        "Exercise & Fitness",
        "Sports Equipment",
        "Outdoor Sports",
        "Team Sports",
        "Golf",
        "Cycling",
        "Yoga & Pilates",
        "Running",
        "Swimming",
        "Tennis",
        "Basketball",
        "Soccer",
        "Baseball",
        "Football",
        "Hockey",
        "Camping & Hiking",
        "Fishing",
        "Hunting",
        "Water Sports",
        "Winter Sports"
    ],
    "Toys & Hobbies": [
        "Action Figures",
        "Dolls & Bears",
        "Building Toys",
        "Games",
        "Model Trains",
        "RC Vehicles",
        "Board Games",
        "Puzzles",
        "Arts & Crafts",
        "Musical Instruments",
        "Collectibles",
        "Trading Cards",
        "Science & Education",
        "Outdoor Toys",
        "Baby & Toddler Toys",
        "Electronic Toys",
        "Toy Vehicles",
        "Pretend Play",
        "Party Supplies",
        "Hobby Tools"
    ],
    "Automotive": [
        "Car Parts & Accessories",
        "Motorcycle Parts",
        "Truck Parts",
        "Tools & Equipment",
        "Car Electronics",
        "Tires & Wheels",
        "Interior Accessories",
        "Exterior Accessories",
        "Lighting",
        "Audio & Video",
        "GPS & Navigation",
        "Car Care",
        "Oils & Fluids",
        "Brakes & Suspension",
        "Engine Parts",
        "Transmission",
        "Body Parts",
        "Performance Parts",
        "Safety Equipment",
        "Motorcycle Gear"
    ],
    "Health & Beauty": [
        "Fragrances",
        "Makeup",
        "Skin Care",
        "Hair Care",
        "Vitamins & Supplements",
        "Personal Care",
        "Bath & Body",
        "Nail Care",
        "Oral Care",
        "Shaving & Hair Removal",
        "Massage & Relaxation",
        "Medical Supplies",
        "Vision Care",
        "Hearing Aids",
        "First Aid",
        "Sexual Wellness",
        "Natural Remedies",
        "Diet & Nutrition",
        "Fitness Equipment",
        "Wellness Products"
    ],
    "Jewelry & Watches": [
        "Fine Jewelry",
        "Fashion Jewelry",
        "Watches",
        "Loose Diamonds",
        "Loose Gemstones",
        "Jewelry Boxes",
        "Men's Watches",
        "Women's Watches",
        "Children's Watches",
        "Smart Watches",
        "Necklaces",
        "Bracelets",
        "Earrings",
        "Rings",
        "Pendants",
        "Brooches & Pins",
        "Anklets",
        "Body Jewelry",
        "Jewelry Sets",
        "Jewelry Care"
    ],
    "Musical Instruments": [
        "Guitars",
        "Keyboards & Pianos",
        "Drums & Percussion",
        "Brass Instruments",
        "Woodwind Instruments",
        "Pro Audio Equipment",
        "String Instruments",
        "Wind Instruments",
        "Percussion Instruments",
        "Electronic Instruments",
        "Accessories",
        "Sheet Music",
        "Recording Equipment",
        "Live Sound",
        "DJ Equipment",
        "Studio Equipment",
        "Cases & Covers",
        "Maintenance & Care",
        "Instruction & Books",
        "Parts & Components"
    ],
    "Office Products": [
        "Office Furniture",
        "Office Electronics",
        "Office Supplies",
        "Printers & Scanners",
        "Presentation Equipment",
        "Shipping Supplies",
        "Desks & Workstations",
        "Chairs",
        "Storage & Organization",
        "Paper Products",
        "Writing Instruments",
        "Notebooks & Pads",
        "Calendars & Planners",
        "Binders & Folders",
        "Labels & Stickers",
        "Envelopes & Mailers",
        "Desk Accessories",
        "Breakroom Supplies",
        "Safety & Security",
        "Office Decor"
    ],
    "Pet Supplies": [
        "Dog Supplies",
        "Cat Supplies",
        "Fish Supplies",
        "Bird Supplies",
        "Reptile Supplies",
        "Small Animal Supplies",
        "Pet Food",
        "Pet Treats",
        "Pet Toys",
        "Pet Beds",
        "Pet Carriers",
        "Pet Grooming",
        "Pet Health",
        "Pet Training",
        "Pet Clothing",
        "Pet Collars & Leashes",
        "Pet Bowls & Feeders",
        "Pet Cleaning",
        "Pet Vitamins",
        "Pet Accessories"
    ],
    "Books & Magazines": [
        "Fiction Books",
        "Non-Fiction Books",
        "Textbooks",
        "Children's Books",
        "Magazines",
        "Audiobooks",
        "Literature",
        "Biographies",
        "Business Books",
        "Cookbooks",
        "Art Books",
        "History Books",
        "Science Books",
        "Travel Books",
        "Self-Help Books",
        "Religious Books",
        "Educational Books",
        "Comic Books",
        "Rare Books",
        "Digital Books"
    ],
    "Industrial & Scientific": [
        "Lab Equipment",
        "Industrial Equipment",
        "Safety Equipment",
        "Electrical Equipment",
        "Material Handling",
        "Test Equipment",
        "Measuring Tools",
        "Power Tools",
        "Hand Tools",
        "Fasteners",
        "Adhesives & Sealants",
        "Paints & Coatings",
        "Cleaning Supplies",
        "Safety Gear",
        "Lab Supplies",
        "Scientific Instruments",
        "Industrial Chemicals",
        "Packaging Materials",
        "Industrial Hardware",
        "Scientific Books"
    ]
}

# Condition mapping
CONDITION_MAP: Dict[str, str] = {
    "New": "NEW",
    "Used": "USED",
    "Refurbished": "REFURBISHED",
    "For parts or not working": "FOR_PARTS_OR_NOT_WORKING"
}

# Sort options mapping
SORT_MAP: Dict[str, str] = {
    "Best Match": "bestMatch",
    "Price: Low to High": "price",
    "Price: High to Low": "-price",
    "Time: ending soonest": "endTime",
    "Time: newly listed": "newlyListed"
} 